[build]
  publish = "_site"
  command = "npm run build"
  functions = "functions"

[[redirects]]
  from = "/thanks"
  to = "/thanks.html"
  status = 200

[[redirects]]
  from = "/contact-thanks"
  to = "/contact-thanks.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# GitHub Webhookを処理する関数へのパス
[[redirects]]
  from = "/api/update-news-index"
  to = "/.netlify/functions/update-news-index"
  status = 200
