# バックエンド設定
backend:
  name: github
  repo: Shima-Chasan/glamping-base-yolo
  branch: main # GitHubのブランチ名
  # Netlifyの環境変数を参照
  token: ${GITHUB_TOKEN}
media_folder: "images/uploads" # メディアファイルのアップロード先
public_folder: "/images/uploads" # 公開時のパス

# 日本語対応
locale: 'ja'

# コンテンツコレクション（編集可能なコンテンツタイプ）
collections:
  - name: "news"
    label: "お知らせ"
    folder: "_data/news"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime", format: "YYYY.MM.DD", date_format: "YYYY.MM.DD", time_format: false}
      - {label: "内容", name: "content", widget: "markdown"}
      - {label: "公開状態", name: "published", widget: "boolean", default: true}
      
  - name: "site_settings"
    label: "サイト設定"
    files:
      - file: "_data/amenities.yml"
        label: "アメニティと備品"
        name: "amenities"
        fields:
          - {label: "セクションタイトル", name: "title", widget: "string"}
          - {label: "アメニティリスト", name: "items", widget: "list"}
              
      - file: "_data/pricing.yml"
        label: "料金プラン"
        name: "pricing"
        fields:
          - {label: "セクションタイトル", name: "title", widget: "string"}
          - label: "基本料金"
            name: "basic_plan"
            widget: "object"
            fields:
              - {label: "タイトル", name: "title", widget: "string"}
              - {label: "プラン名", name: "name", widget: "string"}
              - {label: "料金", name: "price", widget: "string"}
              - {label: "詳細情報", name: "notes", widget: "list"}
          - label: "オプション"
            name: "options"
            widget: "object"
            fields:
              - {label: "タイトル", name: "title", widget: "string"}
              - label: "オプション項目"
                name: "items"
                widget: "list"
                fields:
                  - {label: "項目名", name: "name", widget: "string"}
                  - {label: "料金", name: "price", widget: "string"}
                  - {label: "詳細", name: "notes", widget: "string"}
          - {label: "注釈", name: "footnote", widget: "string"}
